### ISSUE TITLE
How to run medallia Word2Vec Java implementation in windows machine

### ISSUE THREAD

**Issue by dwijenrudrapal** [medallia/Word2VecJava#13]
Sir,
I got the llink https://github.com/medallia/Word2VecJava as word2vec java implementation. I would like to run the implementation in my windows machine. currently i am using Netbean 8 for java development along with maven.
Thanks in advance.

**Comment by guerda** [comment]
Thanks for your interest in word2vecJava, @dwijenrudrapal !
You can include word2vec-java via Maven as a dependency, as seen in the [README.md](https://github.com/medallia/Word2VecJava/blob/master/README.md).
In [com.medallia.word2vec.Word2VecTest](https://github.com/medallia/Word2VecJava/blob/master/src/test/java/com/medallia/word2vec/Word2VecTest.java) you can see different test cases how you can start the algorithm on your data.

**Comment by dwijenrudrapal** [comment]
Thank you sir.

I will let you know regarding the status.

Regards
Dwijen

**Comment by dwijenrudrapal** [comment]
Sir,
medallia-word2vec is showing error while i run the function
[searcher.cosineDistance("money", "Honey")]
Error comes like
Exception in thread "main"
com.medallia.word2vec.Searcher$UnknownWordException: Unknown search word
'Honey'
at com.medallia.word2vec.SearcherImpl.getVector(SearcherImpl.java:83)
at com.medallia.word2vec.SearcherImpl.cosineDistance(SearcherImpl.java:45)
at
com.medallia.word2vec.Word2VecExamples.interact(Word2VecExamples.java:130)
at com.medallia.word2vec.Word2VecExamples.demoWord(Word2VecExamples.java:73)

Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec
(default-cli) on project medallia-word2vec: Command execution failed.
Process exited with an error: 1 (Exit value: 1) -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read
the following articles:
[Help 1]
http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException.

PLease i need kind help.

**Comment by guerda** [comment]
The error you receive here is the same as in #21. Please try to use different text corpus and/or training settings to search for words you want. UnknownWordException its not uncommon, but not avoidable by the framework. You have to deal with unknown words in your own code.

**Comment by guerda** [comment]
@wko27 would you be so kind and close this issue as resolved? Thanks!
