### ISSUE TITLE
Model load takes a very long time!

### ISSUE THREAD

**Issue by sbhaktha** [medallia/Word2VecJava#14]
I am using the `Word2VecModel.fromBinFile(modelFile)` API to open the default word2vec model, `GoogleNews-vectors-negative300.bin` (https://code.google.com/p/word2vec/). The model is ~3.6 gigs. My program has been stuck loading this model for more than an hour now. Heap usage is at 11 gigs. 

What is the expected load time for a model this size? Why is it taking 11 gigs for a 3.6 gig model? 
Would converting the model to the Thrift format be a solution?

Appreciate your help!

Regards,
Sumithra

**Comment by dirkgr** [comment]
Loading that model takes a lot of time in `SwappedDataInputStream.readFloat()`. 99%, according to YourKit.
