### ISSUE TITLE
Utilizing only one CPU

### ISSUE THREAD

**Issue by eclecticlogic** [medallia/Word2VecJava#16]
I'm running the Word2vec example on Linux with Java 8 on an core i7 processor (allocated 8GB of ram to the java process) and I see only one CPU pegged at 100% (numThreads is set to 20). What should I look into?

**Comment by wko27** [comment]
Hmm, that's odd.  The TrainingProgressListener class should output the
current stage of processing.  Can you verify that it's in the "train neural
network" phase when there's only 1 CPU being used?  We didn't parallelize
any of the prior steps.

If that wasn't the issue, then I would add debugging logic to
NeuralNetworkTrainer.train around line 156.  We're using a thread pool with
a fixed size set to the numThreads parameter.

Cheers,
Andrew

**Comment by eclecticlogic** [comment]
Yes, it is the train neural network that uses only 1 CPU. This is not an issue then.
