### ISSUE TITLE
jar available on a public maven repo

### ISSUE THREAD

**Issue by shark8me** [medallia/Word2VecJava#2]
Hi,

I'd like to know if this project build is available as a jar on a public Maven or Gradle repository? I'd like to use it without needing to drop the sources into my project.

Thanks!

**Comment by guerda** [comment]
Here are the basic information how to publish to OSSRH and then to Maven Central: http://central.sonatype.org/pages/ossrh-guide.html

**Comment by wko27** [comment]
Hello!

Working on it :)

We'd like to add support for reading Word2Vec text files before releasing the jar.

Cheers,
Andrew

**Comment by guerda** [comment]
@wko27 I can definitely help you with the Maven central deployment. Just drop me a line if you need support.

**Comment by yibinlin** [comment]
@guerda  thank you we will contact you should we have questions :)

**Comment by yfpeng** [comment]
I second this proposal and add the pom.xml for maven repo. I sent a pull request, if you are interested.

**Comment by yibinlin** [comment]
@yfpeng Thank you for the help! We have merged your pull request :)

**Comment by yibinlin** [comment]
We have pushed a change to read Word2Vec text model file. Will most likely publish a jar version in maven central next week.

**Comment by guerda** [comment]
@yibinlin Have you published it into the snapshot repository already? I can offer testing the snapshot.

**Comment by yibinlin** [comment]
Sorry haven't finished it yet. Sonatype ticket has been approved, and I need to go from there

**Comment by yibinlin** [comment]
published in maven central as 0.9.0 version.

**Comment by shark8me** [comment]
What's the groupid:artifactid with which this jar was published? I can't seem to find it using a search on mvnrepository (http://mvnrepository.com/search?q=word2vecjava)

**Comment by yibinlin** [comment]
Hi @shark8me : it is here: http://search.maven.org/#search|ga|1|word2vecjava with groupid: com.medallia.word2vec artifact id: Word2VecJava

**Comment by guerda** [comment]
Thanks everyone! I was able to include it into my project including source download etc.
Thanks!

**Comment by yibinlin** [comment]
@guerda you are welcome! Excited to see the project in Maven Central
