### ISSUE TITLE
Cut a new release and publish it?

### ISSUE THREAD

**Issue by dirkgr** [medallia/Word2VecJava#25]
Could I trouble you to make a new release and upload it to Maven? We are currently using this in a bunch of projects by copying the jar file around, but it would be much better if we could depend on the latest in Maven.

Cheers!

**Comment by dirkgr** [comment]
Ping?

**Comment by wko27** [comment]
Hey, I checked and I don't think I have permissions to publish a new release in Maven.  My co-author for this project is coming back on Tuesday and I'll ask him to do so then!  Sorry for the trouble!

**Comment by dirkgr** [comment]
No worries, thank you!

**Comment by Hronom** [comment]
Waiting for miracles in maven central repository:stuck_out_tongue:

**Comment by dirkgr** [comment]
Thanks for looking into it!

**Comment by Hronom** [comment]
I'm not a maintainer of releases, I'm just a regular user that still wait new version in maven central:sleeping:

**Comment by yibinlin** [comment]
The release 0.10.3 should be searchable in two hours. Thanks,

Yibin

**Comment by dirkgr** [comment]
Yay! Thank you!
