### ISSUE TITLE
Bad 0.10.2 release in maven central

### ISSUE THREAD

**Issue by Hronom** [medallia/Word2VecJava#26]
http://search.maven.org/#search%7Cga%7C1%7CWord2VecJava
In maven central, the 0.10.2 release has an groupid`com.medallia.word4vec` instead of `com.medallia.word2vec`. Is this a misprint?

**Comment by yibinlin** [comment]
Hi @Hronom - Yes you are right. This release has some issues with this release and we will try to fix it in a day or two.

Thanks
Yibin

**Comment by yibinlin** [comment]
Fixed release with 0.10.3, please try in two hours or later in Maven Central. 

Also please let us know if you see other problems by opening an issue :)
