### ISSUE TITLE
DeepLearning 4j

### ISSUE THREAD

**Issue by AbhiMangal** [medallia/Word2VecJava#32]
cd C:\Users\Abhilasha\Documents\NetBeansProjects\dl4j-0.4-examples-master; "JAVA_HOME=C:\Program Files\Java\jdk1.8.0" cmd /c "\"\"C:\Program Files\NetBeans 8.0.1\java\maven\bin\mvn.bat\" -Dexec.args=\"-classpath %classpath org.deeplearning4j.examples.rnn.GravesLSTMCharModellingExample\" -Dexec.executable=\"C:\Program Files\Java\jdk1.8.0\bin\java.exe\" -Dexec.classpathScope=runtime -Dmaven.ext.class.path=\"C:\Program Files\NetBeans 8.0.1\java\maven-nblib\netbeans-eventspy.jar\" org.codehaus.mojo:exec-maven-plugin:1.2.1:exec\""
Running NetBeans Compile On Save execution. Phase execution is skipped and output directories of dependency projects (with Compile on Save turned on) will be used instead of their jar artifacts.
Scanning for projects...

Some problems were encountered while building the effective model for org.deeplearning4j:deeplearning4j-examples:jar:0.4-rc0-SNAPSHOT
'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 146, column 21

It is highly recommended to fix these problems because they threaten the stability of your build.

For this reason, future Maven versions might no longer support building such malformed projects.

---
## Building DeepLearning4j Examples 0.4-rc0-SNAPSHOT

--- exec-maven-plugin:1.2.1:exec (default-cli) @ deeplearning4j-examples ---
File downloaded to C:\Users\ABHILA~1\AppData\Local\Temp\Shakespeare.txt
Loaded and converted file: 5459809 valid characters of 5465100 total characters (5291 removed)
SLF4J: The requested version 1.6 by your slf4j binding is not compatible with [1.5.5, 1.5.6, 1.5.7, 1.5.8]
SLF4J: See http://www.slf4j.org/codes.html#version_mismatch for further details.
Exception in thread "main" java.lang.ExceptionInInitializerError: unable to load from [netlib-native_system-win-x86_64.dll]
    at com.github.fommil.jni.JniLoader.load(JniLoader.java:81)
    at com.github.fommil.netlib.NativeSystemBLAS.<clinit>(NativeSystemBLAS.java:42)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:259)
    at org.nd4j.linalg.cpu.BlasWrapper.<clinit>(BlasWrapper.java:41)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:259)
    at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:4532)
    at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:4490)
    at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:136)
    at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.seed(NeuralNetConfiguration.java:415)
## BUILD FAILURE

Total time: 1:01.600s
Finished at: Tue Oct 27 21:24:13 IST 2015
## Final Memory: 12M/165M

Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project deeplearning4j-examples: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by guerda** [comment]
This does not seem to be word2vec java, but deeplearning4j. Are you sure you are running word2vec by medallia?

**Comment by wko27** [comment]
Marking as closed!
