### ISSUE TITLE
Read from bin file

### ISSUE THREAD

**Issue by yfpeng** [medallia/Word2VecJava#4]
I think it will be very helpful if we have a new functionality of reading word2vec bin model file, so we can use many available trained files in binary format. I can definitely help you with it if no one is currently working on it.

**Comment by c0der1337** [comment]
Good idea, I m interested in it, too.

**Comment by guerda** [comment]
I'm currently looking into it. I will try to work on it and create a branch. Let's see if I understand the file format completely. The C code in the original is not quite familiar to me.

**Comment by blumonkey** [comment]
Hi @guerda, 
Did you find a way to load a bin model?

**Comment by guerda** [comment]
Hi @blumonkey!
Sorry, I was not able to parse that format for this Java port.
